-- MySQL Script generated by MySQL Workbench
-- Sat Nov  7 23:23:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Estacionamento
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Estacionamento` ;

-- -----------------------------------------------------
-- Schema Estacionamento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Estacionamento` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Estacionamento` ;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `CPF` INT NULL,
  `Telefone` INT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ticket` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ticket` (
  `idTicket` INT NOT NULL,
  `HoraEntrada` DATETIME NULL,
  `HoraSaida` DATETIME NULL,
  `Valor` DOUBLE NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`idTicket`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vaga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vaga` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Vaga` (
  `idVaga` INT NOT NULL,
  `NomeVaga` VARCHAR(45) NULL,
  `Ticket_idTicket` INT NOT NULL,
  PRIMARY KEY (`idVaga`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Veiculo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Veiculo` (
  `idVeiculo` INT NOT NULL,
  `Placa` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Cor` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Vaga_idVaga` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
